services:
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    depends_on:
      - db

  db:
    image: ${POSTGRES_IMAGE}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  ### Adicionando o banco do Keycloak
  keycloak-db:
    image: ${POSTGRES_IMAGE}
    container_name: keycloak_db
    environment:
      POSTGRES_DB: ${KC_DB_NAME}
      POSTGRES_USER: ${KC_DB_USER}
      POSTGRES_PASSWORD: ${KC_DB_PASS}
    volumes:
      - keycloak_data:/var/lib/postgresql/data

  ### Adicionando o Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    command: start-dev
    environment:
      - KC_DB=${KC_DB}
      - KC_DB_URL=${KC_DB_URL}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}

      # Desative quando for usar locamente e ative para usar no GITPOD
      #- KC_HTTP_ENABLED=${KC_HTTP_ENABLED} # permite comunicação HTTP (sem TLS) mesmo com redirect HTTPS
      #- KC_PROXY=${KC_PROXY}      
      #- KC_HOSTNAME_STRICT=${KC_HOSTNAME_STRICT}     # Temporário, apenas durante DESENV: Isso permite que o Keycloak aceite qualquer hostname
      #- KC_HOSTNAME=${KC_HOSTNAME} # define o domínio público do Keycloak no Gitpod
     
    ports:
      - "8081:8080"
    depends_on:
      - keycloak-db
        
## adiciona key cloack
volumes:
  pgdata:
  keycloak_data: